trigger:
  branches:
    include:
      - main
      - dev

variables:
  vmImageName: 'ubuntu-latest'
  mavenVersion: '3.9.6'
  javaVersion: '17'
  projectName: 'skillmate'
  artifactName: 'skillmate-jar'

stages:
  - stage: Build
    displayName: 'Build e Testes'
    jobs:
      - job: BuildAndTest
        displayName: 'Build, Testar e Publicar Artefatos'
        pool:
          vmImage: $(vmImageName)
        
        steps:
          - checkout: self
            displayName: 'Checkout do código'

          - task: JavaToolInstaller@0
            displayName: 'Instalar Java 17'
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'

          - task: Bash@3
            displayName: 'Criar diretório Maven'
            inputs:
              targetType: 'inline'
              script: |
                mkdir -p $(Pipeline.Workspace)/.m2/repository

          - task: Cache@2
            displayName: 'Cache de Dependências Maven'
            inputs:
              key: 'maven | "$(Agent.OS)" | pom.xml'
              restoreKeys: |
                maven | "$(Agent.OS)"
              path: '$(Pipeline.Workspace)/.m2/repository'

          - task: Maven@4
            displayName: 'Restaurar dependências Maven'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'dependency:resolve'
              options: '-U -Dmaven.repo.local=$(Pipeline.Workspace)/.m2/repository'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              jdkArchitectureOption: 'x64'

          - task: Maven@4
            displayName: 'Build da aplicação'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              options: '-DskipTests -Dmaven.repo.local=$(Pipeline.Workspace)/.m2/repository'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: false

          - task: Bash@3
            displayName: 'Copiar JAR para diretório de staging'
            inputs:
              targetType: 'inline'
              script: |
                mkdir -p $(Build.ArtifactStagingDirectory)/jar
                cp $(System.DefaultWorkingDirectory)/target/$(projectName)-*.jar $(Build.ArtifactStagingDirectory)/jar/
                ls -la $(Build.ArtifactStagingDirectory)/jar/

          - task: PublishBuildArtifacts@1
            displayName: 'Publicar artefato de build'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)/jar'
              artifactName: '$(artifactName)'
              publishLocation: 'Container'
